version: '2'

services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "1234:1234"
    depends_on:
      - mongodb
    networks:
      - app_mongo
  
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app_mongo

networks:
  app_mongo:
    driver: bridge